The following ABNF grammar defines the Wallet Access Protocol:

    WAP = open ( traffic / heartbeat ) close

    open = C:OPEN ( S:OPEN-OK / S:ERROR )

    traffic = blocks / put / get_tx / save_bc / start / stop / o_indexes / random_outs / height / info / peer_list / mining_status / log_hash_rate / log_level / start_save_graph / stop_save_graph / block_hash / block_template / get_hard_fork_info / connections_list / stop_daemon / get_block_by_height / get_block_by_hash / get_key_image_status / get_tx_pool

    blocks = C:BLOCKS ( S:BLOCKS-OK / S:ERROR )
    send_raw_transaction = C:SEND-RAW-TRANSACTION ( S:SEND-RAW-TRANSACTION-OK / S:ERROR )
    get_tx = C:GET-TX ( S:GET-TX-OK / S:ERROR )
    save_bc = C:SAVE-BC ( S:SAVE-BC-OK / S:ERROR )
    start = C:START ( S:START-OK / S:ERROR )
    stop = C:STOP ( S:STOP-OK / S:ERROR )
    o_indexes = C:OUTPUT-INDEXES ( S:OUTPUT-INDEXES-OK / S:ERROR )
    random_outs = C:RANDOM-OUTS ( S:RANDOM-OUTS-OK / S:ERROR )
    height = C:GET-HEIGHT ( S:GET-HEIGHT-OK / S:ERROR )
    info = C:GET-INFO ( S:GET-INFO-OK / S:ERROR )
    peer_list = C:GET-PEER-LIST ( S:GET-PEER-LIST-OK / S:ERROR )
    mining_status = C:GET-MINING-STATUS ( S:GET-MINING-STATUS-OK / S:ERROR )
    log_hash_rate = C:SET-LOG-HASH-RATE ( S:SET-LOG-HASH-RATE-OK / S:ERROR )
    log_level = C:SET-LOG-LEVEL ( S:SET-LOG-LEVEL-OK / S:ERROR )
    start_save_graph = C:START-SAVE-GRAPH ( S:START-SAVE-GRAPH-OK / S:ERROR )
    stop_save_graph = C:STOP-SAVE-GRAPH ( S:STOP-SAVE-GRAPH-OK / S:ERROR )
    block_hash = C:GET-BLOCK-HASH ( S:GET-BLOCK-HASH-OK / S:ERROR )
    block_template = C:GET-BLOCK-TEMPLATE ( S:GET-BLOCK-TEMPLATE-OK / S:ERROR )
    get_hard_fork_info = C:GET-HARD-FORK-INFO ( S:GET-HARD-FORK-INFO-OK / S:ERROR )
    connections_list = C:GET-CONNECTIONS-LIST ( S:GET-CONNECTIONS-LIST-OK / S:ERROR )
    stop_daemon = C:STOP-DAEMON ( S:STOP-DAEMON-OK / S:ERROR )
    get_block_by_height = C:GET-BLOCK-BY-HEIGHT ( S:GET-BLOCK-BY-HEIGHT-OK / S:ERROR )
    get_block_by_hash = C:GET-BLOCK-BY-HASH ( S:GET-BLOCK-BY-HASH-OK / S:ERROR )
    get_key_image_status = C:GET-KEY-IMAGE-STATUS ( S:GET-KEY-IMAGE-STATUS-OK / S:ERROR )
    get_tx_pool = C:GET-TX-POOL ( S:GET-TX-POOL-OK / S:ERROR )

    heartbeat = C:PING ( S:PING-OK / S:ERROR )

    close = C:CLOSE ( S:CLOSE-OK / S:ERROR )

    ;  Wallet opens a connection to the daemon.                              

    OPEN            = signature %d1 protocol version identity
    signature       = %xAA %xA0             ; two octets
    protocol        = string                ; 
    version         = number-2              ; Protocol version 1
    identity        = string                ; Wallet identity

    ;  Daemon accepts wallet open request.                                   

    OPEN-OK         = signature %d2

    ;  Wallet requests a set of blocks from the daemon. Daemon replies with  
    ;  BLOCKS-OK, or ERROR if the request is invalid.                        

    BLOCKS          = signature %d3 block_ids start_height
    block_ids       = strings               ; 
    start_height    = number-8              ; 

    ;  Daemon returns a set of blocks to the wallet.                         

    BLOCKS-OK       = signature %d4 status start_height curr_height block_data
    status          = number-4              ; Status
    start_height    = number-8              ; 
    curr_height     = number-8              ; 
    block_data      = msg                   ; Frames of block data

    ;  Wallet sends a raw transaction to the daemon. Daemon replies with     
    ;  SEND-RAW-TRANSACTION-OK, or ERROR.                                    

    SEND-RAW-TRANSACTION = signature %d5 tx_as_hex
    tx_as_hex       = chunk                 ; Transaction as hex

    ;  Daemon confirms that it accepted the raw transaction.                 

    SEND-RAW-TRANSACTION-OK = signature %d6 status
    status          = number-4              ; Status

    ;  Ask for tx output indexes.                                            

    OUTPUT-INDEXES  = signature %d7 tx_id
    tx_id           = chunk                 ; Transaction ID

    ;  Daemon returns tx output indexes.                                     

    OUTPUT-INDEXES-OK = signature %d8 status o_indexes
    status          = number-4              ; Status
    o_indexes       = frame                 ; Output Indexes

    ;  Get random outputs for amounts.                                       

    RANDOM-OUTS     = signature %d9 outs_count amounts
    outs_count      = number-8              ; Outs count
    amounts         = frame                 ; Amounts

    ;  Daemon returns random outputs for amounts.                            

    RANDOM-OUTS-OK  = signature %d10 status random_outputs
    status          = number-4              ; Status
    random_outputs  = frame                 ; Outputs

    ;  Get height.                                                           

    GET-HEIGHT      = signature %d11

    ;  Daemon returns height.                                                

    GET-HEIGHT-OK   = signature %d12 status height
    status          = number-4              ; Status
    height          = number-8              ; Height

    ;  Wallet requests transaction data from the daemon. Daemon replies with 
    ;  GET-OK, or ERROR.                                                     

    GET-TX          = signature %d13 tx_id as_json
    tx_id           = chunk                 ; Transaction ID
    as_json         = number-1              ; As JSON

    ;  Daemon replies with transaction data.                                 

    GET-TX-OK       = signature %d14 status tx_data in_pool
    status          = number-4              ; Status
    tx_data         = chunk                 ; Transaction data
    in_pool         = number-1              ; In pool

    ;  save_bc command. Details tbd.                                         

    SAVE-BC         = signature %d15

    ;  Daemon replies to a save_bc command.                                  

    SAVE-BC-OK      = signature %d16 status
    status          = number-4              ; Status

    ;  Wallet asks daemon to start mining. Daemon replies with START-OK, or  
    ;  ERROR.                                                                

    START           = signature %d17 address thread_count
    address         = chunk                 ; 
    thread_count    = number-8              ; 

    ;  Daemon replies to a start mining request.                             

    START-OK        = signature %d18 status
    status          = number-4              ; 

    ;  getinfo IPC                                                           

    GET-INFO        = signature %d19

    ;  No description                                                        

    GET-INFO-OK     = signature %d20 status height target_height difficulty tx_count tx_pool_size alt_blocks_count outgoing_connections_count incoming_connections_count white_peerlist_size grey_peerlist_size testnet
    status          = number-4              ; Status
    height          = number-8              ; Height
    target_height   = number-8              ; Target Height
    difficulty      = number-8              ; Difficulty
    tx_count        = number-8              ; TX Count
    tx_pool_size    = number-8              ; TX Pool Size
    alt_blocks_count = number-8             ; Alt Blocks Count
    outgoing_connections_count = number-8   ; Outgoing Connections Count
    incoming_connections_count = number-8   ; Incoming Connections Count
    white_peerlist_size = number-8          ; White Peerlist Size
    grey_peerlist_size = number-8           ; Grey Peerlist Size
    testnet         = number-1              ; Testnet

    ;  get_peer_list IPC                                                     

    GET-PEER-LIST   = signature %d21

    ;  No description                                                        

    GET-PEER-LIST-OK = signature %d22 status white_list gray_list
    status          = number-4              ; Status
    white_list      = frame                 ; White list
    gray_list       = frame                 ; Gray list

    ;  get_mining_status IPC                                                 

    GET-MINING-STATUS = signature %d23

    ;  No description                                                        

    GET-MINING-STATUS-OK = signature %d24 status active speed thread_count address
    status          = number-4              ; Status
    active          = number-1              ; Active
    speed           = number-8              ; Speed
    thread_count    = number-8              ; Threads count
    address         = chunk                 ; Address

    ;  set_log_hash_rate IPC                                                 

    SET-LOG-HASH-RATE = signature %d25 visible
    visible         = number-1              ; Visible

    ;  No description                                                        

    SET-LOG-HASH-RATE-OK = signature %d26 status
    status          = number-4              ; Status

    ;  set_log_level IPC                                                     

    SET-LOG-LEVEL   = signature %d27 level
    level           = number-1              ; Level

    ;  No description                                                        

    SET-LOG-LEVEL-OK = signature %d28 status
    status          = number-4              ; Status

    ;  start_save_graph IPC                                                  

    START-SAVE-GRAPH = signature %d29

    ;  No description                                                        

    START-SAVE-GRAPH-OK = signature %d30 status
    status          = number-4              ; Status

    ;  stop_save_graph IPC                                                   

    STOP-SAVE-GRAPH = signature %d31

    ;  No description                                                        

    STOP-SAVE-GRAPH-OK = signature %d32 status
    status          = number-4              ; Status

    ;  get_block_hash IPC                                                    

    GET-BLOCK-HASH  = signature %d33 height
    height          = number-8              ; Height

    ;  No description                                                        

    GET-BLOCK-HASH-OK = signature %d34 status hash
    status          = number-4              ; Status
    hash            = chunk                 ; Hash

    ;  get_block_template IPC                                                

    GET-BLOCK-TEMPLATE = signature %d35 reserve_size address
    reserve_size    = number-8              ; Reserve size
    address         = chunk                 ; Address

    ;  No description                                                        

    GET-BLOCK-TEMPLATE-OK = signature %d36 status reserved_offset height difficulty prev_hash block_template_blob
    status          = number-4              ; Status
    reserved_offset = number-8              ; Rservered Offset
    height          = number-8              ; Height
    difficulty      = number-8              ; Difficulty
    prev_hash       = chunk                 ; Previous Hash
    block_template_blob = chunk             ; Block template blob

    ;  Wallet asks daemon to start mining. Daemon replies with STOP-OK, or   
    ;  ERROR.                                                                

    STOP            = signature %d37

    ;  Daemon replies to a stop mining request.                              

    STOP-OK         = signature %d38

    ;  get_hard_fork_info IPC                                                

    GET-HARD-FORK-INFO = signature %d39 hfversion
    hfversion       = number-1              ; Version

    ;  No description                                                        

    GET-HARD-FORK-INFO-OK = signature %d40 status hfversion enabled window votes threshold voting hfstate
    status          = number-4              ; Status
    hfversion       = number-1              ; Version
    enabled         = number-1              ; Enabled
    window          = number-4              ; Window
    votes           = number-4              ; Votes
    threshold       = number-4              ; Threshold
    voting          = number-1              ; Voting
    hfstate         = number-4              ; State

    ;  get_connections_list IPC                                              

    GET-CONNECTIONS-LIST = signature %d41

    ;  No description                                                        

    GET-CONNECTIONS-LIST-OK = signature %d42 status connections
    status          = number-4              ; Status
    connections     = frame                 ; Connections

    ;  stop_daemon IPC                                                       

    STOP-DAEMON     = signature %d43

    ;  No description                                                        

    STOP-DAEMON-OK  = signature %d44 status
    status          = number-4              ; Status

    ;  get_block_by_height IPC                                               

    GET-BLOCK-BY-HEIGHT = signature %d45 height header_only as_json
    height          = number-8              ; Height
    header_only     = number-1              ; Header-only
    as_json         = number-1              ; As JSON

    ;  No description                                                        

    GET-BLOCK-BY-HEIGHT-OK = signature %d46 status block major_version minor_version timestamp prev_hash nonce orphan height depth hash difficulty reward
    status          = number-4              ; Status
    block           = chunk                 ; Block blob
    major_version   = number-1              ; 
    minor_version   = number-1              ; 
    timestamp       = number-8              ; 
    prev_hash       = chunk                 ; 
    nonce           = number-4              ; 
    orphan          = number-1              ; 
    height          = number-8              ; 
    depth           = number-8              ; 
    hash            = chunk                 ; 
    difficulty      = number-8              ; 
    reward          = number-8              ; 

    ;  get_block_by_hash IPC                                                 

    GET-BLOCK-BY-HASH = signature %d47 hash header_only as_json
    hash            = chunk                 ; Hash
    header_only     = number-1              ; Header-only
    as_json         = number-1              ; As JSON

    ;  No description                                                        

    GET-BLOCK-BY-HASH-OK = signature %d48 status block major_version minor_version timestamp prev_hash nonce height depth hash difficulty reward
    status          = number-4              ; Status
    block           = chunk                 ; Block blob
    major_version   = number-1              ; 
    minor_version   = number-1              ; 
    timestamp       = number-8              ; 
    prev_hash       = chunk                 ; 
    nonce           = number-4              ; 
    height          = number-8              ; 
    depth           = number-8              ; 
    hash            = chunk                 ; 
    difficulty      = number-8              ; 
    reward          = number-8              ; 

    ;  Request whether key images are spent                                  

    GET-KEY-IMAGE-STATUS = signature %d49 key_images
    key_images      = frame                 ; 

    ;  Daemon returns spent status for the key images.                       

    GET-KEY-IMAGE-STATUS-OK = signature %d50 status spent
    status          = number-4              ; Status
    spent           = frame                 ; Key image spent status

    ;  Wallet requests the tx pool from the daemon.                          

    GET-TX-POOL     = signature %d51

    ;  Daemon returns a set of transactions to the wallet.                   

    GET-TX-POOL-OK  = signature %d52 status tx_pool_data
    status          = number-4              ; Status
    tx_pool_data    = msg                   ; Frames of transaction data

    ;  Wallet closes the connection. This is polite though not mandatory.    
    ;  Daemon will reply with CLOSE-OK or ERROR.                             

    CLOSE           = signature %d53

    ;  Daemon replies to a wallet connection close request.                  

    CLOSE-OK        = signature %d54

    ;  Wallet heartbeats an idle connection.                                 

    PING            = signature %d55

    ;  Daemon replies to a wallet ping request.                              

    PING-OK         = signature %d56

    ;  Daemon replies with failure status. Status codes tbd.                 

    ERROR           = signature %d57 status reason
    status          = number-2              ; Error status
    reason          = string                ; Printable explanation

    ; A list of string values
    strings         = strings-count *strings-value
    strings-count   = number-4
    strings-value   = longstr

    ; A chunk has 4-octet length + binary contents
    chunk           = number-4 *OCTET

    ; A frame is zero or more octets encoded as a ZeroMQ frame
    frame           = *OCTET

    ; A msg is zero or more distinct frames
    msg             = *frame

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
